server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:8889/sova
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        show_sql: true
        use_sql_comments: true
        format_sql: true
        query:
          immutable_entity_update_query_handling_mode: exception
        jdbc:
          time_zone: "UTC"
          lob:
            non_contextual_creation: true

        cache:
          use_second_level_cache: true
          use_reference_entries: true
          use_query_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            config: "redisson.yaml"
            fallback: true
            entity:
              eviction:
                max_entries: 10000
                expiration:
                  time_to_live: 120000
                  max_idle_time: 120000
              default-query-results-region:
                eviction:
                  max_entries: 500
                expiration:
                  time_to_live: 43200000
                  max_idle_time: 86400000
              default-update-timestamps-region:
                eviction:
                  max_entries: 50
                expiration:
                  time_to_live: 86400000
                  max_idle_time: 86400000
              user:
                eviction:
                  max_entries: 5000
                expiration:
                  time_to_live: 600000
                  max_idle_time: 1800000

        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: file:/Users/pavelazarenko/Desktop/Work/java/FirstCache/src/main/resources/jcache.xml